import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, writeFile, mkdir } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import { checkSnippet, acceptSnippet, readCommittedSnippet, SNIPPET_PATH } from '../build/mcp-snippet-check.mjs';
import { renderSnippet, planShards } from '../build/mcp-shards.mjs';

const GENERATED = renderSnippet({ '0050': 6, '70B3': 6, '8C1F': 6 });

async function sandbox() {
  return mkdtemp(path.join(os.tmpdir(), 'mcp-drift-'));
}

test('a missing committed copy reports absent, not stale', async () => {
  const root = await sandbox();
  const state = await checkSnippet({ root, generated: GENERATED });
  assert.equal(state.status, 'absent');
  assert.match(state.reason, /does not exist/);
});

test('an identical copy reports current', async () => {
  const root = await sandbox();
  await acceptSnippet({ root, generated: GENERATED });
  const state = await checkSnippet({ root, generated: GENERATED });
  assert.equal(state.status, 'current');
});

test('a committed copy with a different route table reports stale', async () => {
  const root = await sandbox();
  // What the zone is actually running: an older table.
  await acceptSnippet({ root, generated: renderSnippet({ '0050': 6 }) });
  // What this build produces: a cluster moved, so the table grew.
  const state = await checkSnippet({ root, generated: GENERATED });
  assert.equal(state.status, 'stale');
  // The message has to name the consequence, because the failure is otherwise
  // a silent wrong answer rather than an error.
  assert.match(state.reason, /no vendor/);
  assert.match(state.reason, /route table/);
});

test('acceptSnippet writes the generated bytes verbatim', async () => {
  const root = await sandbox();
  await acceptSnippet({ root, generated: GENERATED });
  const onDisk = await readFile(path.join(root, SNIPPET_PATH), 'utf8');
  assert.equal(onDisk, GENERATED);
  assert.equal(await readCommittedSnippet(root), GENERATED);
});

test('the committed copy is a real ES module, not a template', async () => {
  const onDisk = await readFile(
    path.join(path.dirname(new URL('../build/mcp-shards.mjs', import.meta.url).pathname), '..', SNIPPET_PATH),
    'utf8',
  );
  assert.match(onDisk, /export default \{/);
  assert.match(onDisk, /^const DEPTH = \{.*\};$/m);
  assert.doesNotMatch(onDisk, /\$\{/, 'no unresolved template interpolation');
  // The 32 KB limit is on the bytes uploaded, and `npm run mcp:deploy` minifies
  // before sending, so the minified size is what has to fit. Cloudflare counts
  // uploaded bytes, verified by upload.
  const { transform } = await import('esbuild');
  const minified = await transform(onDisk, { loader: 'js', minify: true, target: 'es2022' });
  assert.ok(
    Buffer.byteLength(minified.code) < 32 * 1024,
    `minified snippet must fit 32 KB, got ${Buffer.byteLength(minified.code)} bytes`,
  );
});

test('the real route table matches the real plan', async () => {
  const plan = planShards([
    { prefix: '0050C2', blockType: 'MA-L', addressCount: 16777216, orgName: 'X', country: 'US' },
    { prefix: '8C1F64A', blockType: 'MA-M', addressCount: 1048576, orgName: 'Y', country: 'US' },
  ]);
  // Small fixture, so nothing is over the target and the table stays empty.
  assert.deepEqual(plan.table, {});
  const snippet = renderSnippet(plan.table);
  assert.match(snippet, /^const DEPTH = \{\};$/m);
});
