/**
 * Stateless MCP endpoint for https://mac.jasontally.com
 *
 * GENERATED by build/mcp-shards.mjs. Do not edit by hand; edit the generator
 * and rebuild. Deploy this file as a Cloudflare Snippet on the zone with a rule
 * whose filter expression is exactly:
 *
 *   (http.host eq "mac.jasontally.com" and (http.request.uri.path eq "/mcp" or http.request.uri.path eq "/mcp/"))
 *
 * The host is in the expression on purpose. A Snippet rule is zone-wide, so a
 * path-only rule also fires on every other subdomain, where the shard fetch
 * below would 404 and every lookup would report no vendor. The HOST check in
 * the handler is the second line of defence for the same mistake.
 *
 * One tool, `lookup`. The model never reads a shard and never picks a key:
 * this snippet normalizes the address, fetches the one shard that can hold the
 * answer, and does the longest-prefix match in code. One subrequest per lookup.
 *
 * No depth in DEPTH exceeds 6, the shortest registered prefix, so a single
 * fetch always carries every candidate prefix. Do not deepen it: a deeper key
 * drops the 6-character MA-L parents and the lookup silently returns no match.
 *
 * Snippet limits: 5 ms execution, 2 MB memory, 32 KB package. No bindings, no
 * storage, no logs.
 */

// Base shard key length in hex characters, and how much deeper the build had to
// carve the dense ranges. Keys are uppercase, matching the normalized query.
const BASE_DEPTH = 4;
const DEPTH = {"0050":6,"70B3":6,"8C1F":6};

const HOST = "mac.jasontally.com";
const SITE = "https://mac.jasontally.com";
const SHARD_PATH = "/data/mcp";
const CATALOG = SHARD_PATH + '/catalog.json';
const HEX = /^[0-9A-F]+$/;
const NO_COUNTRY = "-";

function headers(extra) {
  return Object.assign(
    {
      'content-type': 'application/json; charset=utf-8',
      'access-control-allow-origin': '*',
      'access-control-allow-methods': 'POST, OPTIONS',
      'access-control-allow-headers':
        'content-type, accept, authorization, mcp-protocol-version, mcp-method, mcp-name, mcp-session-id',
      'access-control-expose-headers': 'mcp-protocol-version, mcp-session-id',
      'cache-control': 'no-store',
    },
    extra || {},
  );
}

function rpcResult(id, result) {
  return new Response(JSON.stringify({ jsonrpc: '2.0', id: id === undefined ? null : id, result }), {
    status: 200,
    headers: headers(),
  });
}

function rpcError(id, code, message, status) {
  return new Response(
    JSON.stringify({ jsonrpc: '2.0', id: id === undefined ? null : id, error: { code, message } }),
    { status: status || 400, headers: headers() },
  );
}

/** Uppercase hex to colon-separated octets. Mirrors src/ui/format.mjs. */
function colonize(hex) {
  return hex.match(/.{1,2}/g).join(':');
}

/** Take the first `count` pipe-separated fields; the remainder is the org name. */
function splitLine(line, count) {
  const fields = [];
  let rest = line;
  for (let i = 0; i < count; i += 1) {
    const at = rest.indexOf('|');
    if (at === -1) {
      fields.push(rest);
      rest = '';
      continue;
    }
    fields.push(rest.slice(0, at));
    rest = rest.slice(at + 1);
  }
  fields.push(rest);
  return fields;
}

/** Fetch one shard or the catalog. GET, so the zone rule cannot re-enter. */
function pull(url) {
  return fetch(new Request(url.toString(), { method: 'GET', headers: { accept: 'application/json, text/plain' } }));
}

/**
 * Read a shard body, or return null when there is nothing to read.
 *
 * The site sets `not_found_handling: "single-page-application"`, so Cloudflare
 * answers *any* unmatched path with HTTP 200 and the SPA shell as text/html. A
 * `response.ok` test is therefore not enough: scanning the SPA shell for
 * pipe-delimited lines finds nothing, and an unguarded scan would read an HTML
 * page as an empty shard. So require the content type, then a record line.
 *
 * Null is NOT treated as a deployment fault, because an empty bucket and a
 * missing bucket are indistinguishable from here, and empty buckets are the
 * common case: 13,571 of the 65,536 possible 4-character keys have records, so
 * 79.3% of them are empty. Raising an error instead would turn most
 * unregistered lookups into 5xx. A null shard means "no registered prefix in
 * this range", which is the honest reading.
 *
 * The whole-deploy case is caught by the catalog instead, which is a single
 * file: if catalog.json will not load, nothing was deployed, and
 * tools/list fails loudly instead of reporting an empty tool list.
 */
async function readShard(response) {
  if (!response.ok) return null;
  if (!/^text\/plain/i.test(response.headers.get('content-type') || '')) return null;
  const text = await response.text();
  return text.indexOf('|') === -1 ? null : text;
}

/** Longest registered prefix of `hex` in one shard body. */
function longestMatch(hex, text) {
  let best = null;
  let bestPrefix = '';
  if (!text) return null;
  for (const line of text.split('\n')) {
    const stop = line.indexOf('|');
    if (stop === -1) continue;
    const prefix = line.slice(0, stop);
    if (prefix.length <= bestPrefix.length || !hex.startsWith(prefix)) continue;
    bestPrefix = prefix;
    best = line;
  }
  return best === null ? null : { prefix: bestPrefix, line: best };
}

async function lookup(request, payload, id) {
  const args = (payload.params && payload.params.arguments) || {};
  const raw = args.mac;
  // Mirrors src/engine/input.mjs: strip separators, uppercase, 6-12 hex only.
  const hex = String(raw === undefined || raw === null ? '' : raw)
    .replace(/[\s:.-]/g, '')
    .toUpperCase();
  if (hex.length < 6) {
    return rpcError(id, -32602, 'Invalid argument "mac": need at least 6 hex characters.');
  }
  if (hex.length > 12) {
    return rpcError(id, -32602, 'Invalid argument "mac": at most 12 hex characters.');
  }
  if (!HEX.test(hex)) {
    return rpcError(id, -32602, 'Invalid argument "mac": not hexadecimal.');
  }

  // One shard holds every candidate prefix, because the routed depth never
  // exceeds the shortest registered prefix.
  const depth = DEPTH[hex.slice(0, BASE_DEPTH)] || BASE_DEPTH;
  const key = hex.slice(0, depth).toLowerCase();
  const body = await readShard(await pull(new URL(SHARD_PATH + '/' + key + '.txt', request.url)));
  const match = longestMatch(hex, body ?? '');

  const query = colonize(hex);
  const first = parseInt(hex.slice(0, 2), 16);
  const local = (first & 0b10) === 2;
  const multicast = (first & 0b1) === 1;

  if (match === null) {
    const why = local
      ? 'no registered prefix covers it; this address is locally administered, which usually means a randomized or virtual-machine address'
      : 'no registered prefix covers it';
    return rpcResult(id, {
      content: [{ type: 'text', text: query + ' - ' + why + '. Randomized addresses have no vendor. See ' + SITE + '/help for block types.' }],
      structuredContent: {
        query,
        prefix: null,
        blockType: null,
        addressCount: null,
        orgName: null,
        country: null,
        locallyAdministered: local,
        multicast,
        url: SITE + '/help',
      },
    });
  }

  const { prefix, line } = match;
  const fields = splitLine(line, 4);
  const blockType = fields[1];
  const addressCount = Number(fields[2]);
  const country = fields[3] === NO_COUNTRY ? null : fields[3];
  const orgName = fields[4];
  const page = SITE + '/' + prefix;

  return rpcResult(id, {
    content: [
      {
        type: 'text',
        text:
          query + ' is inside ' + prefix + ', an ' + blockType + ' block of ' +
          addressCount.toLocaleString('en-US') + ' addresses' +
          (country ? ' registered in ' + country : '') + ', held by ' + orgName +
          '. Full record, including the organization address: ' + page,
      },
    ],
    structuredContent: { query, prefix, blockType, addressCount, orgName, country, url: page },
  });
}

/**
 * Protocol version this server speaks, and the only one it speaks.
 *
 * 2026-07-28 only. There is no legacy lane, so the version has to be stated
 * rather than negotiated down.
 */
const PROTOCOL_VERSION = '2026-07-28';

/**
 * Versions this endpoint can serve statelessly. Each is a *request* contract,
 * not a session contract: the same one-fetch handler serves all of them, and
 * none of them gets a Mcp-Session-Id. The handshake is accepted so a client
 * whose connection flow probes with initialize is not turned away.
 */
const LEGACY_HANDSHAKE = true;
const SUPPORTED_VERSIONS = ["2026-07-28","2025-11-25","2025-06-18"];
/**
 * Largest request body the endpoint will read.
 *
 * A tools/call is ~110 bytes and tools/list is ~30, so this is generous by two
 * orders of magnitude while keeping the worst case small enough to parse inside
 * the snippet memory budget. See the guard at the parse site.
 */
const MAX_BODY_BYTES = 4096;
const SERVER_NAME = 'mac-address-lookup';
const SERVER_TITLE = 'MAC Address Lookup';
const SERVER_VERSION = '1.0.0';
const SERVER_INSTRUCTIONS =
  'Public, read-only MAC address and OUI lookup derived from the IEEE Registration ' +
  'Authority registries. Call lookup once per address. The record page at the ' +
  'returned url carries the organization address, the block range, and ownership ' +
  'history.';

/**
 * Reject a request that names a protocol version we do not speak.
 *
 * This is the affordance the transition depends on, and returning -32601
 * instead quietly breaks it. A client that prefers another modern revision is
 * supposed to receive UnsupportedProtocolVersionError (-32022) listing what the
 * server does support, select a mutually supported version, and retry in place.
 * A client-side era check treats -32022 as proof the server is modern; an
 * unrecognized 400 is the signal for a *legacy* server. So -32601 makes a modern
 * server look like a legacy one, and sends the client down a fallback path that
 * cannot work.
 */
function versionError(id, requested) {
  return new Response(
    JSON.stringify({
      jsonrpc: '2.0',
      id: id === undefined ? null : id,
      error: {
        code: -32022,
        message:
          'Unsupported protocol version' +
          (requested ? ': ' + requested : '') +
          '. This server accepts ' + SUPPORTED_VERSIONS.join(', ') + '.',
        data: { supported: SUPPORTED_VERSIONS, ...(requested ? { requested } : {}) },
      },
    }),
    { status: 400, headers: headers() },
  );
}

/**
 * The protocol version a request claims, from any of the places it can appear.
 *
 * The order matters and the bug it caused is worth recording. initialize
 * carries its version in params.protocolVersion. That is the only place a real
 * client ever sends it, because 2025-03-26 removed the header requirement from
 * the handshake. An earlier version of this function read only the header and
 * _meta, so on initialize it returned null, the guard was skipped, and the reply
 * fell through to "negotiate to whatever we like". A client asking for
 * 2024-11-05 was told the server speaks 2026-07-28, then refused on every later
 * request, having been waved through at the door.
 *
 * params.protocolVersion is therefore read first, so a stale header cannot
 * shadow the version under test.
 */
function claimedVersion(request, payload) {
  const params = payload && payload.params;
  if (params && typeof params === 'object') {
    const inParams = params.protocolVersion;
    if (typeof inParams === 'string' && inParams) return inParams.trim();
    // A non-string version is a malformed request, not an absent one. Coerce it
    // so it is refused rather than silently treated as not supplied.
    if (typeof inParams === 'number') return String(inParams);
    // _meta lives under params, not at the top level. Check both.
    const meta = params._meta;
    if (meta && typeof meta === 'object') {
      const key = 'io.modelcontextprotocol/protocolVersion';
      if (typeof meta[key] === 'string') return meta[key].trim();
    }
  }
  const fromHeader = request.headers.get('mcp-protocol-version');
  if (fromHeader) return fromHeader.trim();
  const topMeta = payload && payload._meta;
  if (topMeta && typeof topMeta === 'object') {
    const key = 'io.modelcontextprotocol/protocolVersion';
    if (typeof topMeta[key] === 'string') return topMeta[key].trim();
  }
  return null;
}

export default {
  async fetch(request) {
    // Second line of defence behind the rule expression. A Snippet rule is
    // zone-wide, so a path-only rule reaches every subdomain. Refusing here
    // turns that misconfiguration into a loud 404 instead of a lookup that
    // fetches shards from the wrong host, 404s every key, and reports no
    // vendor for every address.
    if (new URL(request.url).host !== HOST) {
      return new Response(
        JSON.stringify({
          jsonrpc: '2.0',
          id: null,
          error: { code: -32601, message: 'Not found: this MCP endpoint is served on ' + HOST + ' only.' },
        }),
        { status: 404, headers: headers() },
      );
    }
    if (request.method === 'OPTIONS') {
      return new Response(null, { status: 204, headers: headers() });
    }
    // The zone rule already filters on POST. This guard is what stops a
    // same-zone subrequest from re-entering the handler.
    if (request.method !== 'POST') {
      return new Response(
        JSON.stringify({ jsonrpc: '2.0', id: null, error: { code: -32600, message: 'This endpoint accepts POST only.' } }),
        { status: 405, headers: headers({ allow: 'POST, OPTIONS' }) },
      );
    }

    // Reject an oversized body on the declared length, before reading it.
    //
    // This endpoint is unauthenticated and unthrottled, so a caller-supplied
    // body size is a free amplification lever. Measured before this guard: a
    // single 90 MB POST was accepted, occupied the invocation for 33.6 seconds
    // of wall clock, and still returned 200. A legitimate lookup is ~110 bytes,
    // so that is roughly 600,000x amplification from one request, repeatable
    // concurrently and without credentials.
    //
    // The check is on Content-Length so it costs nothing: the body is never
    // read, so a hostile client never gets the invocation to spend. A chunked
    // request with no declared length still reaches the platform body limit,
    // but it cannot be used to skip this check cheaply, because streaming a
    // large body costs the caller bandwidth and the server time either way.
    const declared = Number(request.headers.get('content-length'));
    if (Number.isFinite(declared) && declared > MAX_BODY_BYTES) {
      return rpcError(null, -32600, 'Request body too large: the limit is ' + MAX_BODY_BYTES + ' bytes.', 413);
    }

    let payload;
    try {
      payload = await request.json();
    } catch {
      return rpcError(null, -32700, 'Parse error: the body is not JSON.');
    }
    if (!payload || typeof payload !== 'object' || Array.isArray(payload)) {
      return rpcError(null, -32600, 'Invalid request: the body is not a JSON-RPC object.');
    }

    // JSON-RPC notification: no id, so no response body.
    if (!Object.hasOwn(payload, 'id')) {
      return new Response(null, { status: 202, headers: headers() });
    }
    const id = payload.id;

    // Reject only a version we genuinely cannot serve. Anything in the
    // supported set is served statelessly, so a 2025-era client is not turned
    // away at the door.
    const claimed = claimedVersion(request, payload);
    if (claimed !== null && !SUPPORTED_VERSIONS.includes(claimed)) {
      return versionError(id, claimed);
    }

    const method = payload.method || request.headers.get('Mcp-Method') || '';
    const toolName = (payload.params && payload.params.name) || request.headers.get('Mcp-Name') || '';

    if (method === 'initialize') {
      // 2026-07-28 removed the handshake, but a connector UI still probes with
      // it. Refusing it costs a 400, and a 400 during the auth check reads as
      // "this server wants sign-in" -- Claude reports that as a configuration
      // error, when the real problem is that the server is too strict.
      //
      // So answer it, statelessly. This is the reference SDK's legacy:stateless
      // mode and Cloudflare's default: accept the handshake, then serve every
      // later request independently. No session is created and no
      // Mcp-Session-Id is ever issued, so the one-fetch, session-free design is
      // unchanged. Set LEGACY_HANDSHAKE to false for a 2026-07-28-only endpoint.
      if (!LEGACY_HANDSHAKE) {
        return versionError(id, claimed);
      }
      // asked is already validated by the guard above: claimedVersion reads
      // params.protocolVersion, so an unsupported version never reaches here.
      // A client that omits it entirely gets the current revision, which is
      // what the pre-header handshake did.
      const asked = claimed === null ? PROTOCOL_VERSION : claimed;
      return rpcResult(id, {
        protocolVersion: asked,
        capabilities: { tools: { listChanged: false } },
        serverInfo: { name: SERVER_NAME, title: SERVER_TITLE, version: SERVER_VERSION },
        ...(asked === PROTOCOL_VERSION ? {} : { instructions: SERVER_INSTRUCTIONS }),
      });
    }

    if (method === 'ping') {
      return rpcResult(id, {});
    }

    if (method === 'tools/list' || method === 'server/discover') {
      const response = await pull(new URL(CATALOG, request.url));
      if (!response.ok) return rpcError(id, -32603, 'Tool catalog is unavailable.');
      // The SPA fallback answers a missing asset with 200 and HTML, so guard the
      // content type before parsing rather than letting json() throw.
      if (!/^application\/json/i.test(response.headers.get('content-type') || '')) {
        return rpcError(id, -32603, 'Tool catalog is unavailable: the path did not return JSON.');
      }
      return rpcResult(id, await response.json());
    }
    if (method === 'tools/call') {
      if (toolName !== 'lookup') {
        return rpcError(id, -32601, 'Unknown tool "' + toolName + '". This server exposes only "lookup".');
      }
      return lookup(request, payload, id);
    }
    return rpcError(id, -32601, 'Unknown method "' + method + '". This server exposes tools/list and tools/call.');
  },
};
